export default {
  // 查询演出列表
  getShowList: 'performance/pc/getListByPage',
  getActiveList: 'activity/queryAll',
  // 赞助商列表
  sponsorList: 'sponsor/queryAll',
  // 增加赞助商
  sponsorAdd: 'sponsor/add',
  // 更新赞助商
  updateById: 'sponsor/updateById',
  // 查询赞助商信息
  querySponsor: 'sponsor/query',
  // 添加和编辑券码
  edit: 'codeType/edit',
  // 查询券码列表
  queryBySponsorId: 'codeType/queryBySponsorId',
  // 查询单个接口
  queryById: 'codeType/queryById',
  // 获取审核问题列表
  getCheckList: 'activityQa/queryAll',
  // 设置问题审核通过
  makeChecked: 'activityQa/updateById',
  // 获取需要审核图片
  getCheckPic: 'activityQaUrl/queryPage',
  // 设置审核图片通过
  setCheckPic: 'activityQaUrl/edit',
  // 批量上传兑换码
  uploadCode: 'changeCode/up'
}